const clearError = async ()=> {
    console.log('error cleared')
}

module.export = clearError